apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
       # Mount the initdb.sh script from the ConfigMap to the appropriate location in the container   
        - name: postgres-config
          mountPath: /docker-entrypoint-initdb.d/initdb.sh
    
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: n8nio-secret
              key: POSTGRES_ROOT_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8nio-secret
              key: POSTGRES_ROOT_PASSWORD
        - name: POSTGRES_NON_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: n8nio-secret
              key: POSTGRES_NON_ROOT_USER
        - name: POSTGRES_NON_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8nio-secret  
              key: POSTGRES_NON_ROOT_PASSWORD      

        - name: POSTGRES_DB
          value: n8n    
      volumes:
       - name: postgres-config
         configMap:
          name: postgres-config     
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432