apiVersion: v1
kind: ResourceQuota
metadata:
  name: n8nio-resource-quota
  namespace: default
spec:
  hard:
    pods: "3"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi   
    services: "2"
    secrets: "2"
    configmaps: "2"
